"""esquema inicial

Revision ID: ce52016a7bd1
Revises:
Create Date: 2026-09-27 19:56:46.376932

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce52016a7bd1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "CategoriaInstrumental",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_CategoriaInstrumental")),
        sa.UniqueConstraint("nombre", name=op.f("uq_CategoriaInstrumental_nombre")),
    )
    op.create_table(
        "DispositivoMedico",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("descripcion", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_DispositivoMedico")),
        sa.UniqueConstraint("nombre", name=op.f("uq_DispositivoMedico_nombre")),
    )
    op.create_table(
        "EquipoBiomedico",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("descripcion", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_EquipoBiomedico")),
        sa.UniqueConstraint("nombre", name=op.f("uq_EquipoBiomedico_nombre")),
    )
    op.create_table(
        "Especialidad",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Especialidad")),
        sa.UniqueConstraint("nombre", name=op.f("uq_Especialidad_nombre")),
    )
    op.create_table(
        "Sutura",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("calibre", sa.String(), nullable=True),
        sa.Column("tipo_aguja", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Sutura")),
        sa.UniqueConstraint(
            "nombre",
            "calibre",
            "tipo_aguja",
            name=op.f("uq_Sutura_nombre_calibre_tipo_aguja"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "Usuario",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column(
            "rol",
            sa.Enum("usuario", "colaborador", "revisor", "admin", name="rol_usuario"),
            server_default="usuario",
            nullable=False,
        ),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "fecha_aceptacion_politica", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column("version_politica", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Usuario")),
        sa.UniqueConstraint("email", name=op.f("uq_Usuario_email")),
    )
    op.create_table(
        "Zona",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Zona")),
        sa.UniqueConstraint("nombre", name=op.f("uq_Zona_nombre")),
    )
    op.create_table(
        "Instrumental",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("categoria_id", sa.Uuid(), nullable=False),
        sa.Column("descripcion", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["CategoriaInstrumental.id"],
            name=op.f("fk_Instrumental_categoria_id_CategoriaInstrumental"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Instrumental")),
        sa.UniqueConstraint("nombre", name=op.f("uq_Instrumental_nombre")),
    )
    op.create_table(
        "Tecnica",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("especialidad_id", sa.Uuid(), nullable=False),
        sa.Column("creado_por", sa.Uuid(), nullable=False),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["creado_por"], ["Usuario.id"], name=op.f("fk_Tecnica_creado_por_Usuario")
        ),
        sa.ForeignKeyConstraint(
            ["especialidad_id"],
            ["Especialidad.id"],
            name=op.f("fk_Tecnica_especialidad_id_Especialidad"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_Tecnica")),
        sa.UniqueConstraint(
            "nombre", "especialidad_id", name=op.f("uq_Tecnica_nombre_especialidad_id")
        ),
    )
    op.create_table(
        "InstrumentalAlias",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("instrumental_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrumental_id"],
            ["Instrumental.id"],
            name=op.f("fk_InstrumentalAlias_instrumental_id_Instrumental"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_InstrumentalAlias")),
        sa.UniqueConstraint("alias", name=op.f("uq_InstrumentalAlias_alias")),
    )
    op.create_table(
        "TecnicaVersion",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("tecnica_id", sa.Uuid(), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "borrador",
                "en_revision",
                "publicada",
                "reemplazada",
                "archivada",
                name="estado_version",
            ),
            server_default="borrador",
            nullable=False,
        ),
        sa.Column("codigo_cups", sa.String(), nullable=True),
        sa.Column("anestesia", sa.String(), nullable=True),
        sa.Column("posicion_paciente", sa.String(), nullable=True),
        sa.Column("ropa", sa.String(), nullable=True),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("indicaciones", sa.Text(), nullable=True),
        sa.Column("complicaciones", sa.Text(), nullable=True),
        sa.Column("tecnica_quirurgica", sa.Text(), nullable=True),
        sa.Column("creado_por", sa.Uuid(), nullable=False),
        sa.Column("revisado_por", sa.Uuid(), nullable=True),
        sa.Column(
            "fecha_creacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "fecha_actualizacion",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("fecha_revision", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(estado IN ('borrador', 'en_revision')) = (revisado_por IS NULL AND fecha_revision IS NULL)",
            name=op.f("ck_TecnicaVersion_revision_coherente"),
        ),
        sa.CheckConstraint(
            "revisado_por <> creado_por",
            name=op.f("ck_TecnicaVersion_sin_autoaprobacion"),
        ),
        sa.ForeignKeyConstraint(
            ["creado_por"],
            ["Usuario.id"],
            name=op.f("fk_TecnicaVersion_creado_por_Usuario"),
        ),
        sa.ForeignKeyConstraint(
            ["revisado_por"],
            ["Usuario.id"],
            name=op.f("fk_TecnicaVersion_revisado_por_Usuario"),
        ),
        sa.ForeignKeyConstraint(
            ["tecnica_id"],
            ["Tecnica.id"],
            name=op.f("fk_TecnicaVersion_tecnica_id_Tecnica"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_TecnicaVersion")),
        sa.UniqueConstraint(
            "tecnica_id", "numero", name=op.f("uq_TecnicaVersion_tecnica_id_numero")
        ),
    )
    op.create_index(
        "un_borrador_por_tecnica",
        "TecnicaVersion",
        ["tecnica_id"],
        unique=True,
        postgresql_where=sa.text("estado IN ('borrador', 'en_revision')"),
    )
    op.create_index(
        "una_publicada_por_tecnica",
        "TecnicaVersion",
        ["tecnica_id"],
        unique=True,
        postgresql_where=sa.text("estado = 'publicada'"),
    )
    op.create_table(
        "ItemTecnica",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("zona_id", sa.Uuid(), nullable=True),
        sa.Column("numero_leyenda", sa.Integer(), nullable=True),
        sa.Column("texto_fuente", sa.String(), nullable=False),
        sa.CheckConstraint(
            "numero_leyenda IS NULL OR zona_id IS NOT NULL",
            name=op.f("ck_ItemTecnica_numero_con_mesa"),
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["TecnicaVersion.id"],
            name=op.f("fk_ItemTecnica_version_id_TecnicaVersion"),
        ),
        sa.ForeignKeyConstraint(
            ["zona_id"], ["Zona.id"], name=op.f("fk_ItemTecnica_zona_id_Zona")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ItemTecnica")),
        sa.UniqueConstraint(
            "id",
            "version_id",
            "zona_id",
            name=op.f("uq_ItemTecnica_id_version_id_zona_id"),
        ),
        sa.UniqueConstraint(
            "version_id",
            "zona_id",
            "numero_leyenda",
            name=op.f("uq_ItemTecnica_version_id_zona_id_numero_leyenda"),
        ),
    )
    op.create_table(
        "TecnicaVersion_DispositivoMedico",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("dispositivo_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dispositivo_id"],
            ["DispositivoMedico.id"],
            name=op.f(
                "fk_TecnicaVersion_DispositivoMedico_dispositivo_id_DispositivoMedico"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["TecnicaVersion.id"],
            name=op.f("fk_TecnicaVersion_DispositivoMedico_version_id_TecnicaVersion"),
        ),
        sa.PrimaryKeyConstraint(
            "version_id",
            "dispositivo_id",
            name=op.f("pk_TecnicaVersion_DispositivoMedico"),
        ),
    )
    op.create_table(
        "TecnicaVersion_EquipoBiomedico",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("equipo_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipo_id"],
            ["EquipoBiomedico.id"],
            name=op.f("fk_TecnicaVersion_EquipoBiomedico_equipo_id_EquipoBiomedico"),
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["TecnicaVersion.id"],
            name=op.f("fk_TecnicaVersion_EquipoBiomedico_version_id_TecnicaVersion"),
        ),
        sa.PrimaryKeyConstraint(
            "version_id", "equipo_id", name=op.f("pk_TecnicaVersion_EquipoBiomedico")
        ),
    )
    op.create_table(
        "TecnicaVersion_Sutura",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("sutura_id", sa.Uuid(), nullable=False),
        sa.Column("uso", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sutura_id"],
            ["Sutura.id"],
            name=op.f("fk_TecnicaVersion_Sutura_sutura_id_Sutura"),
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["TecnicaVersion.id"],
            name=op.f("fk_TecnicaVersion_Sutura_version_id_TecnicaVersion"),
        ),
        sa.PrimaryKeyConstraint(
            "version_id", "sutura_id", name=op.f("pk_TecnicaVersion_Sutura")
        ),
    )
    op.create_table(
        "ItemTecnicaComponente",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("instrumental_id", sa.Uuid(), nullable=True),
        sa.Column("sutura_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "num_nonnulls(instrumental_id, sutura_id) = 1",
            name=op.f("ck_ItemTecnicaComponente_componente_exactamente_uno"),
        ),
        sa.ForeignKeyConstraint(
            ["instrumental_id"],
            ["Instrumental.id"],
            name=op.f("fk_ItemTecnicaComponente_instrumental_id_Instrumental"),
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["ItemTecnica.id"],
            name=op.f("fk_ItemTecnicaComponente_item_id_ItemTecnica"),
        ),
        sa.ForeignKeyConstraint(
            ["sutura_id"],
            ["Sutura.id"],
            name=op.f("fk_ItemTecnicaComponente_sutura_id_Sutura"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ItemTecnicaComponente")),
    )
    op.create_table(
        "PosicionMesa",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("zona_id", sa.Uuid(), nullable=False),
        sa.Column("fila", sa.Integer(), nullable=False),
        sa.Column("columna", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "fila >= 1 AND columna >= 1", name=op.f("ck_PosicionMesa_celda_valida")
        ),
        sa.ForeignKeyConstraint(
            ["item_id", "version_id", "zona_id"],
            ["ItemTecnica.id", "ItemTecnica.version_id", "ItemTecnica.zona_id"],
            name=op.f("fk_PosicionMesa_item_id_version_id_zona_id_ItemTecnica"),
        ),
        sa.ForeignKeyConstraint(
            ["zona_id"], ["Zona.id"], name=op.f("fk_PosicionMesa_zona_id_Zona")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_PosicionMesa")),
        sa.UniqueConstraint(
            "version_id",
            "zona_id",
            "fila",
            "columna",
            name=op.f("uq_PosicionMesa_version_id_zona_id_fila_columna"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("PosicionMesa")
    op.drop_table("ItemTecnicaComponente")
    op.drop_table("TecnicaVersion_Sutura")
    op.drop_table("TecnicaVersion_EquipoBiomedico")
    op.drop_table("TecnicaVersion_DispositivoMedico")
    op.drop_table("ItemTecnica")
    op.drop_index(
        "una_publicada_por_tecnica",
        table_name="TecnicaVersion",
        postgresql_where=sa.text("estado = 'publicada'"),
    )
    op.drop_index(
        "un_borrador_por_tecnica",
        table_name="TecnicaVersion",
        postgresql_where=sa.text("estado IN ('borrador', 'en_revision')"),
    )
    op.drop_table("TecnicaVersion")
    op.drop_table("InstrumentalAlias")
    op.drop_table("Tecnica")
    op.drop_table("Instrumental")
    op.drop_table("Zona")
    op.drop_table("Usuario")
    op.drop_table("Sutura")
    op.drop_table("Especialidad")
    op.drop_table("EquipoBiomedico")
    op.drop_table("DispositivoMedico")
    op.drop_table("CategoriaInstrumental")
    # Alembic no borra los tipos enum al borrar las tablas: se hace a mano.
    sa.Enum(name="estado_version").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="rol_usuario").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
