"""agregar rechazo de versiones

Revision ID: 83e1e81aa546
Revises: 80ca4b548995
Create Date: 2026-10-07 13:06:53.598461

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83e1e81aa546"
down_revision: str | Sequence[str] | None = "80ca4b548995"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "RechazoVersion",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("rechazado_por", sa.Uuid(), nullable=False),
        sa.Column("motivo", sa.Text(), nullable=False),
        sa.Column(
            "fecha",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(motivo) <> ''", name=op.f("ck_RechazoVersion_motivo_no_vacio")
        ),
        sa.ForeignKeyConstraint(
            ["rechazado_por"],
            ["Usuario.id"],
            name=op.f("fk_RechazoVersion_rechazado_por_Usuario"),
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["TecnicaVersion.id"],
            name=op.f("fk_RechazoVersion_version_id_TecnicaVersion"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_RechazoVersion")),
    )
    op.create_index(
        op.f("ix_RechazoVersion_version_id"),
        "RechazoVersion",
        ["version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_RechazoVersion_version_id"), table_name="RechazoVersion")
    op.drop_table("RechazoVersion")
    # ### end Alembic commands ###
